### ISSUE TITLE
Veranstaltung am 8.6

### ISSUE THREAD

**Issue by CodeKittey** [WAWSS16/Organization#10]
Hey Leute gerade erhielt ich folgende Mail:
_________________________--
Sehr geehrte Frau Kraus,

wieder einmal findet während Ihrer Veranstaltung WAW eine Veranstaltung zum Praxissemester statt. Für die Studierenden der 3. Semester ist der Besuch dieser Veranstaltung, als Vorbereitung für ihr eigenes Praxissemester, verpflichtend.

Der Termin für diese Veranstaltung ist Mittwoch, 8.6.2016, 15:30 - 17:00 Uhr. Wäre es für Sie möglich, einen Ersatztermin für Ihre Vorlesung zu finden, damit die Studierenden aus 3UIB an dieser Veranstaltung teilnehmen können? Da der Termin am 8.6. sowohl von den Studierenden aller 5. und 6. Semester als auch aller 3. Semester wahrgenommen werden muss, ist es leider nicht möglich, hierfür einen geeigneteren Termin zu finden.

Mit freundlichen Grüßen,

Steffen Rasenat
Praktikantenamtsleiter Informatik
_____________________________________________-

D.h. wir müssen nächste Woche uns einen Ersatztermin überlegen.
(Schaue auch nochmal in euren Stundenplan) Ich brauch die beiden Stunden leider :/

**Comment by Rahtainka** [comment]
Könnten wir nicht Mittwochs die eine Stunde machen? Dann müssen wir nicht zwei Stunden am Stück finden. 
Wie wäre denn Montag in unserer Freistunde?
11:30 - 13:00 Uhr 
Oder nächsten Mittwoch 3 Stunden :D

**Comment by CodeKittey** [comment]
haha danke :D
Hmm wenn es für alle i.O ist würde ich wieder Montags 11:30 - 13:30 im A107 kommen?!

**Comment by CodeKittey** [comment]
Da keine Reaktion erfolgt nehme ich das mal als agreement hin :laughing:

**Comment by Rahtainka** [comment]
Montag wäre dann der 30.5. ?

**Comment by SvenjaHering** [comment]
Also dann Montag 6.6. die zweite vom Mittwoch vorziehen und Mittwoch die erst 13:40-15:10 stattfinden lassen?

**Comment by CodeKittey** [comment]
Jap genauso.
Also *nicht* morgen.
Sondern den 8.6 13:40-15:10 und die zweite Stunde nicht
Montag den 6.6 dann 11:30-13uhr

**Comment by DerSiKa** [comment]
Mir ist gerade aufgefallen, dass wir am 6.6. schon einen zusätzlichen Block ST von 11:30 - 13:00 Uhr haben.

**Comment by CodeKittey** [comment]
Als ob ST so wichtig wie WAW ist :p
Hmm ok am besten reden wir einfach nochmal am Mittwoch darüber :)

**Comment by CodeKittey** [comment]
Okay dann Donnerstag 9.6 von 15:20-16:50
Raum tba

**Comment by CodeKittey** [comment]
Oki Update: hab einen Raum gefunden
Donnerstag im 5.Bloch dann in Raum A107

**Comment by CodeKittey** [comment]
Reminder: Morgen findet nichts statt.
Wir sehen uns zum Testat naechste Woche!
