### ISSUE TITLE
MFW no grades

### ISSUE THREAD

**Issue by 1423444** [WAWSS16/Organization#12]
![](https://hugelolcdn.com/i/396590.png)
😏 😏 😏 😏

**Comment by CodeKittey** [comment]
403 bedeutet aber eher, dass man nicht autorisiert ist ;)

Heute Abend geht's die letzten durch, dann lad ich es hoch.
Wie gesagt 13Uhr bin ich an der HS im Raum A010 falls
es noch fragen bzgl dem Code gibt :)

**Comment by 1423444** [comment]
Jaaa aber das was fehlt ist doch 404 😄 😄 😄 😄
