### ISSUE TITLE
Meilenstein 2

### ISSUE THREAD

**Issue by Rahtainka** [WAWSS16/Organization#2]
@CodeKittey 
Hi Martina,

ich wollte mal fragen ob du uns so schnell wie möglich den 2. Meilenstein hoch laden könntest, damit wir bis nächste Woche Montag genug Zeit haben den umzusetzen.

Liebe Grüße 
Katharina

**Comment by CodeKittey** [comment]
Hallo,

der zweite Meilenstein wurde soeben released.
Da WAW auch einmal ausfallen musste, hab ich das Testat um eine Woche auf den 11.5
(und einchecken bis 9.5) verschoben.

VG und bis morgen
Martina
