### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Pathen85** [WAWSS16/Organization#3]
Hey,

bei dem Repo vom Server in WAWSS16 kann man noch kein Issue erstellen oder sollen wir die Issues dazu in das Original-Repo unter CodeKittey machen?

Und der Server ist gerade down..wann ist er denn voraussichtlich wieder erreichbar? :grin:

**Comment by CodeKittey** [comment]
Hey,

nun kann man Issues dort erstellen...
So ein Server ist oftmals down ;)
Entsprechende Fehlerbehandlung ist immer gut ;)

**Comment by CodeKittey** [comment]
und ich hatte schonwieder Angst, dass du mir eine Frage stellst :) :p
@Pathen85

**Comment by Pathen85** [comment]
Wenn du unbedingt willst, kann ich mir gerne noch eine ausdenken :smile:

**Comment by CodeKittey** [comment]
Ja ich sehen mich schon danach ...

und nach Katzen-Smilys ;)
:smirk_cat: 
:joy_cat:
