### ISSUE TITLE
Kleine Frage

### ISSUE THREAD

**Issue by Rahtainka** [WAWSS16/Organization#4]
Hi Martina @CodeKittey,

wäre es nicht sinnvoller beim Geburtsjahr Zahlen von 1900 - 2016 zu erlauben?
Also nicht von 0 bis 2016.

Liebe Grüße
Katharina

**Comment by CodeKittey** [comment]
Hi,
klar, das war nur der einfachheitshalber mehr oder weniger.
Gerne koennt ihr auch das Geburtsjahr ab 1900 starten :)
