### ISSUE TITLE
Fragestunde Montag 9.5

### ISSUE THREAD

**Issue by CodeKittey** [WAWSS16/Organization#5]
Hallo Zusammen,

da ja Mittwoch fuer Fragen ausgefallen ist, hat man mich gebeten, dennoch 

nochmal vor Mittwoch kurz an die HS zu kommen um nochmal eventuelle Fragen 

zu beantworten.

Ich schlage folgendes vor:

Ihr habt Montag (9.5)  2. und 4. Block, deshalb werde ich dann im 3.Block an die HS kommen.

Raum muss ich noch abklaeren.

Die Deadline fuer das Repo pushen verschiebe ich deshalb auch auf 11.5 um 13Uhr.

Ist kein Pflichttermin, nur falls jemand noch fragen hat;

VG,

**Comment by Pathen85** [comment]
In welchem Raum findet dann die Fragestunde statt?

Gruß
Henrik

**Comment by CodeKittey** [comment]
Wir treffen uns erstmal zwischen A010 und A008.
Der 010er ist leider belegt, der 008er könnte aber mit Glück frei haben :)
Ganz Notfalls müssten wir wohl auf den A107er ausweichen.

**Comment by CodeKittey** [comment]
Everything was awesome :)))))
