### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by 1423444** [WAWSS16/Organization#7]
@CodeKittey Kannst du uns die weiteres Milestones schon einsehen lassen, damit wir uns in den Ferien vorbereiten können?
Ohne dass sich das Abgabedatum ändert versteht sich  :stuck_out_tongue_winking_eye:

**Comment by CodeKittey** [comment]
Eine gute Idee.
Ich will nämlich schon das Backend in zwei Meilensteinen aufteilen.
Den 3ten kann ich über das Wochenende dann releasen :) :)

**Comment by 1423444** [comment]
Aber nicht die Abgabe nach vorne verlegen ja 😏

**Comment by CodeKittey** [comment]
Naja die abgae ist dann 23.5 und das Testat 25.5 ;)

**Comment by Rahtainka** [comment]
Ping

**Comment by CodeKittey** [comment]
Pong! jaaaaa sorry ;/
Ich hab dieses Wochenende an dem Mannheimer Halbmarathon teilgenommen (wieso hab ich niemanden von euch dort gesehen? ;-) ) und war danach echt echt fertig :D 
Ich denke ich komme morgen dazu!
Bzw. Bin mir recht sicher, dass ich morgen dazu komme.

**Comment by Rahtainka** [comment]
Ich finde joggen langweilig :X 
Du hast noch 43 Minuten 🙈 falls du mit "morgen" heute gemeint hast.

**Comment by Rahtainka** [comment]
Ich hab nix gesagt :D

**Comment by CodeKittey** [comment]
Morgen ist erst nach dem Aufstehen :beers:

**Comment by CodeKittey** [comment]
Meilenstein 3 wurde released.
**Die Abgabe muss (mindestens) in EcmaScript6 (http://es6-features.org/) Standard erfolgen**
Was das genau bedeutet und was NodeJS oder Express ueberhaupt ist, darauf gehen wir definitiv auch nach den Ferien nochmal ein.

Dann geniesst mal noch schoen Pfingsten ihr kleinen Nervensaegen ;) :) :)

**Comment by Rahtainka** [comment]
Ist Pfingsten nicht schon vorbei? 😜

**Comment by CodeKittey** [comment]
Aber Ferien habt ihr ja trotzdem noch :cat:

**Comment by 1423444** [comment]
Pfingsten ist erst vorbei, wenn auch der Kater vorbei ist 😃 🍺

**Comment by CodeKittey** [comment]
Das ist die richtige Einstellung?

Und alles gut? Habe gerade 2 Tage nichts mehr von euch gehoert. Das macht mich skeptisch.
Ich mache mir doch Sorgen um euch ;-)

**Comment by Rahtainka** [comment]
Wo bleiben unsere Noten und Bewertungen und Feedback????!!!!!!!11111einseinself 😆 

So besser? 👅

**Comment by CodeKittey** [comment]
LOL
...aehm ... da war was.
Stimmt. Ich meinte natuerlich dieses Wochenende *pfeif*

**Comment by 1423444** [comment]
1 Tag verzug = 1 Note besser
Wir vermissen natürlich unsere Dozentin, also geht es uns natürlich schlecht! Und wenn dir nicht schlecht ist von dem Jüngsten deiner viiielen Kater und Katzen, dann aber jetzt wenigstens von der ekelhaften Schleimerei. Gern geschehen, da kannst du dir einen Abend saufen sparen und gleich kotzen 😆

**Comment by CodeKittey** [comment]
Also ich habe in euren Ferien (ich hab ja keine ;/ ) natuerlich nichts getrunken :smirk_cat: 

Btw: ich sehe mir gerade euren Code genauer an und heute Abend/ Nacht lade ich dann die Punkte hoch.

**Comment by Rahtainka** [comment]
Mal so eine klitze kleine Frage... 
Wann ist genau "dann" ? :D 

*duck* *renn*

**Comment by CodeKittey** [comment]
Jetzt :p

**Comment by CodeKittey** [comment]
Das kann geschlossen werden right? ;)
